package instant.Absyn; // Java Package generated by the BNF Converter.

import instant.Context;

public abstract class Expression implements java.io.Serializable {
    int depth = 0;

    public String getName() {
        return "undefined_expression";
    }

    public String getCode(Context context){
        return "misssing implementation";
    }

    public abstract <R> R accept(Expression.Visitor<R> v, Context arg);

    public interface Visitor<R> {
        public R visit(instant.Absyn.AdditionExpression p, Context arg);

        public R visit(instant.Absyn.SubtractExpression p, Context arg);

        public R visit(instant.Absyn.MultiplyExpression p, Context arg);

        public R visit(instant.Absyn.DivideExpression p, Context arg);

        public R visit(instant.Absyn.LiteralExpression p, Context arg);

        public R visit(instant.Absyn.VarExpression p, Context arg);

    }

}
