package instant.Absyn; // Java Package generated by the BNF Converter.

import instant.Context;

public class LiteralExpression extends Expression {
    public final Integer integer_;

    public LiteralExpression(Integer p1) {
        integer_ = p1;
    }

    public <R> R accept(instant.Absyn.Expression.Visitor<R> v, Context arg) {
        return v.visit(this, arg);
    }

    public boolean equals(java.lang.Object o) {
        if (this == o) return true;
        if (o instanceof instant.Absyn.LiteralExpression) {
            instant.Absyn.LiteralExpression x = (instant.Absyn.LiteralExpression) o;
            return this.integer_.equals(x.integer_);
        }
        return false;
    }

    public int hashCode() {
        return this.integer_.hashCode();
    }


}
