package instant.Absyn; // Java Package generated by the BNF Converter.

import instant.Context;

public class MultiplyExpression extends Expression {
    public final Expression expression_1, expression_2;

    public MultiplyExpression(Expression p1, Expression p2) {
        expression_1 = p1;
        expression_2 = p2;
    }

    public <R> R accept(instant.Absyn.Expression.Visitor<R> v, Context arg) {
        return v.visit(this, arg);
    }

    public boolean equals(java.lang.Object o) {
        if (this == o) return true;
        if (o instanceof instant.Absyn.MultiplyExpression) {
            instant.Absyn.MultiplyExpression x = (instant.Absyn.MultiplyExpression) o;
            return this.expression_1.equals(x.expression_1) && this.expression_2.equals(x.expression_2);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.expression_1.hashCode()) + this.expression_2.hashCode();
    }


}
