package instant.Absyn; // Java Package generated by the BNF Converter.

import instant.Context;

public class Prog extends Program {
    public final ListStatement liststatement_;

    public Prog(ListStatement p1) {
        liststatement_ = p1;
    }

    public <R> R accept(instant.Absyn.Program.Visitor<R> v, Context arg) {
        System.out.println("Prog.accept");
        return v.visit(this, arg);
    }

    public boolean equals(java.lang.Object o) {
        if (this == o) return true;
        if (o instanceof instant.Absyn.Prog) {
            instant.Absyn.Prog x = (instant.Absyn.Prog) o;
            return this.liststatement_.equals(x.liststatement_);
        }
        return false;
    }

    public int hashCode() {
        return this.liststatement_.hashCode();
    }


}
