package instant.Absyn; // Java Package generated by the BNF Converter.

import instant.Context;

public abstract class Program implements java.io.Serializable {
    public abstract <R> R accept(Program.Visitor<R> v, Context arg);

    public interface Visitor<R> {
        public R visit(instant.Absyn.Prog p, Context arg);

    }

}
