package instant.Absyn; // Java Package generated by the BNF Converter.

import instant.Context;

public class SAssignment extends Statement {
    public final String ident_;
    public final Expression expression_;

    public SAssignment(String p1, Expression p2) {
        ident_ = p1;
        expression_ = p2;
    }

    public <R> R accept(instant.Absyn.Statement.Visitor<R> v, Context arg) {
        return v.visit(this, arg);
    }

    public boolean equals(java.lang.Object o) {
        if (this == o) return true;
        if (o instanceof instant.Absyn.SAssignment) {
            instant.Absyn.SAssignment x = (instant.Absyn.SAssignment) o;
            return this.ident_.equals(x.ident_) && this.expression_.equals(x.expression_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.ident_.hashCode()) + this.expression_.hashCode();
    }


}
