package instant.Absyn; // Java Package generated by the BNF Converter.

import instant.Context;

public abstract class Statement implements java.io.Serializable {
    public abstract <R> R accept(Statement.Visitor<R> v, Context arg);

    public interface Visitor<R> {
        public R visit(instant.Absyn.SAssignment p, Context arg);

        public R visit(instant.Absyn.SExpression p, Context arg);

    }

}
