package instant.Absyn; // Java Package generated by the BNF Converter.

import instant.Context;

public class VarExpression extends Expression {
    public final String ident_;

    public VarExpression(String p1) {
        ident_ = p1;
    }

    public <R> R accept(instant.Absyn.Expression.Visitor<R> v, Context arg) {
        return v.visit(this, arg);
    }

    public boolean equals(java.lang.Object o) {
        if (this == o) return true;
        if (o instanceof instant.Absyn.VarExpression) {
            instant.Absyn.VarExpression x = (instant.Absyn.VarExpression) o;
            return this.ident_.equals(x.ident_);
        }
        return false;
    }

    public int hashCode() {
        return this.ident_.hashCode();
    }


}
